# Generated by Django 2.2.7 on 2019-11-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hatchback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('stock', models.IntegerField()),
                ('wait_time', models.CharField(default='In stock, no waiting!', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sedan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('stock', models.IntegerField()),
                ('wait_time', models.CharField(default='In stock, no waiting!', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SUVMUV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('stock', models.IntegerField()),
                ('wait_time', models.CharField(default='In stock, no waiting!', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='van',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('stock', models.IntegerField()),
                ('wait_time', models.CharField(default='In stock, no waiting!', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
